In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

In [2]:
# Read the csv file into a pandas DataFrame for transforming (xform all the non-numeric data for ML prep)
xform_pd = pd.read_csv('Voter_final_clean.csv')
xform_pd.head(2)

,Year,State,General:VEP Turnout Rate,General:Total Ballots Counted,VEP,Total registered,Primary:VEP Turnout Rate,Primary:Total Ballots Counted
0,2000,Alabama,59.00%,"1,912,592","3,241,682","2,411,000",15.30%,"489,573"
1,2004,Alabama,57.40%,"1,890,317","3,292,608","2,418,000",26.00%,"863,695"

In [3]:
from sklearn.preprocessing import LabelEncoder 
labelencoder= LabelEncoder() #initializing an object of class LabelEncoder
xform_pd['State'] = labelencoder.fit_transform(xform_pd['State']) #fitting and transforming the desired categorical column.
xform_pd.head(2)

,Year,State,General:VEP Turnout Rate,General:Total Ballots Counted,VEP,Total registered,Primary:VEP Turnout Rate,Primary:Total Ballots Counted
0,2000,0,59.00%,"1,912,592","3,241,682","2,411,000",15.30%,"489,573"
1,2004,0,57.40%,"1,890,317","3,292,608","2,418,000",26.00%,"863,695"

In [4]:
labelencoder.inverse_transform(xform_pd['State'])

array(['Alabama', 'Alabama', 'Alabama', 'Alabama', 'Alabama', 'Alaska',
       'Alaska', 'Alaska', 'Alaska', 'Alaska', 'Arizona', 'Arizona',
       'Arizona', 'Arizona', 'Arizona', 'Arkansas', 'Arkansas',
       'Arkansas', 'Arkansas', 'Arkansas', 'California', 'California',
       'California', 'California', 'California', 'Colorado', 'Colorado',
       'Colorado', 'Colorado', 'Colorado', 'Connecticut', 'Connecticut',
       'Connecticut', 'Connecticut', 'Connecticut', 'Delaware',
       'Delaware', 'Delaware', 'Delaware', 'Delaware',
       'DistrictOfColumbia', 'DistrictOfColumbia', 'DistrictOfColumbia',
       'DistrictOfColumbia', 'DistrictOfColumbia', 'Florida', 'Florida',
       'Florida', 'Florida', 'Florida', 'Georgia', 'Georgia', 'Georgia',
       'Georgia', 'Georgia', 'Hawaii', 'Hawaii', 'Hawaii', 'Hawaii',
       'Hawaii', 'Idaho', 'Idaho', 'Idaho', 'Idaho', 'Idaho', 'Illinois',
       'Illinois', 'Illinois', 'Illinois', 'Illinois', 'Indiana',
       'Indiana', 'Indiana', 'Indiana', 'Indiana', 'Iowa', 'Iowa', 'Iowa',
       'Iowa', 'Iowa', 'Kansas', 'Kansas', 'Kansas', 'Kansas', 'Kansas',
       'Kentucky', 'Kentucky', 'Kentucky', 'Kentucky', 'Kentucky',
       'Louisiana', 'Louisiana', 'Louisiana', 'Louisiana', 'Louisiana',
       'Maine', 'Maine', 'Maine', 'Maine', 'Maine', 'Maryland',
       'Maryland', 'Maryland', 'Maryland', 'Maryland', 'Massachusetts',
       'Massachusetts', 'Massachusetts', 'Massachusetts', 'Massachusetts',
       'Michigan', 'Michigan', 'Michigan', 'Michigan', 'Michigan',
       'Minnesota', 'Minnesota', 'Minnesota', 'Minnesota', 'Minnesota',
       'Mississippi', 'Mississippi', 'Mississippi', 'Mississippi',
       'Mississippi', 'Missouri', 'Missouri', 'Missouri', 'Missouri',
       'Missouri', 'Montana', 'Montana', 'Montana', 'Montana', 'Montana',
       'Nebraska', 'Nebraska', 'Nebraska', 'Nebraska', 'Nebraska',
       'Nevada', 'Nevada', 'Nevada', 'Nevada', 'Nevada', 'NewHampshire',
       'NewHampshire', 'NewHampshire', 'NewHampshire', 'NewHampshire',
       'NewJersey', 'NewJersey', 'NewJersey', 'NewJersey', 'NewJersey',
       'NewMexico', 'NewMexico', 'NewMexico', 'NewMexico', 'NewMexico',
       'NewYork', 'NewYork', 'NewYork', 'NewYork', 'NewYork',
       'NorthCarolina', 'NorthCarolina', 'NorthCarolina', 'NorthCarolina',
       'NorthCarolina', 'NorthDakota', 'NorthDakota', 'NorthDakota',
       'NorthDakota', 'NorthDakota', 'Ohio', 'Ohio', 'Ohio', 'Ohio',
       'Ohio', 'Oklahoma', 'Oklahoma', 'Oklahoma', 'Oklahoma', 'Oklahoma',
       'Oregon', 'Oregon', 'Oregon', 'Oregon', 'Oregon', 'Pennsylvania',
       'Pennsylvania', 'Pennsylvania', 'Pennsylvania', 'Pennsylvania',
       'RhodeIsland', 'RhodeIsland', 'RhodeIsland', 'RhodeIsland',
       'RhodeIsland', 'SouthCarolina', 'SouthCarolina', 'SouthCarolina',
       'SouthCarolina', 'SouthCarolina', 'SouthDakota', 'SouthDakota',
       'SouthDakota', 'SouthDakota', 'SouthDakota', 'Tennessee',
       'Tennessee', 'Tennessee', 'Tennessee', 'Tennessee', 'Texas',
       'Texas', 'Texas', 'Texas', 'Texas', 'Utah', 'Utah', 'Utah', 'Utah',
       'Utah', 'Vermont', 'Vermont', 'Vermont', 'Vermont', 'Vermont',
       'Virginia', 'Virginia', 'Virginia', 'Virginia', 'Virginia',
       'Washington', 'Washington', 'Washington', 'Washington',
       'Washington', 'WestVirginia', 'WestVirginia', 'WestVirginia',
       'WestVirginia', 'WestVirginia', 'Wisconsin', 'Wisconsin',
       'Wisconsin', 'Wisconsin', 'Wisconsin', 'Wyoming', 'Wyoming',
       'Wyoming', 'Wyoming', 'Wyoming'], dtype=object)

In [5]:
#add new column
xform_pd["Re-election"] = 0

In [6]:
xform_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Year                           255 non-null    int64
 1   State                          255 non-null    int32
 2   General:VEP Turnout Rate       255 non-null    object
 3   General:Total Ballots Counted  255 non-null    object
 4   VEP                            255 non-null    object
 5   Total registered               255 non-null    object
 6   Primary:VEP Turnout Rate       255 non-null    object
 7   Primary:Total Ballots Counted  255 non-null    object
 8   Re-election                    255 non-null    int64
dtypes: int32(1), int64(2), object(6)
memory usage: 17.1+ KB

In [7]:
# label election year 0 and relection year 1
xform_pd.loc[xform_pd["Year"].isin([2004,2012]),"Re-election"] = 1
xform_pd

,Year,State,General:VEP Turnout Rate,General:Total Ballots Counted,VEP,Total registered,Primary:VEP Turnout Rate,Primary:Total Ballots Counted,Re-election
0,2000,0,59.00%,"1,912,592","3,241,682","2,411,000",15.30%,"489,573",0
1,2004,0,57.40%,"1,890,317","3,292,608","2,418,000",26.00%,"863,695",1
2,2008,0,61.00%,"2,105,622","3,454,510","2,438,000",32.20%,"1,088,835",0
3,2012,0,59.00%,"2,088,138","3,539,217","2,556,000",24.80%,"871,025",1
4,2016,0,59.10%,"2,134,061","3,609,447","2,526,000",35.00%,"1,260,551",0
...,...,...,...,...,...,...,...,...,...
250,2000,50,61.40%,"221,685","361,078","240,000",2.00%,"7,096",0
251,2004,50,66.30%,"245,789","370,785","265,000",2.00%,"7,545",1
252,2008,50,63.10%,"256,035","405,732","270,000",2.60%,"9,953",0
253,2012,50,59.00%,"250,701","425,142","268,000",0.30%,"1,308",1
254,2016,50,60.20%,"258,788","429,682","304,000",2.00%,"8,568",0

In [8]:
#convert data type, remove % and replace
# https://www.geeksforgeeks.org/python-pandas-series-astype-to-convert-data-type-of-series/
#      data["Salary"]= data["Salary"].astype(int) 
#      data["Number"]= data["Number"].astype(str)

xform_pd["General:VEP Turnout Rate"]= xform_pd["General:VEP Turnout Rate"].str.replace("%","").astype(float) 
xform_pd

,Year,State,General:VEP Turnout Rate,General:Total Ballots Counted,VEP,Total registered,Primary:VEP Turnout Rate,Primary:Total Ballots Counted,Re-election
0,2000,0,59.0,"1,912,592","3,241,682","2,411,000",15.30%,"489,573",0
1,2004,0,57.4,"1,890,317","3,292,608","2,418,000",26.00%,"863,695",1
2,2008,0,61.0,"2,105,622","3,454,510","2,438,000",32.20%,"1,088,835",0
3,2012,0,59.0,"2,088,138","3,539,217","2,556,000",24.80%,"871,025",1
4,2016,0,59.1,"2,134,061","3,609,447","2,526,000",35.00%,"1,260,551",0
...,...,...,...,...,...,...,...,...,...
250,2000,50,61.4,"221,685","361,078","240,000",2.00%,"7,096",0
251,2004,50,66.3,"245,789","370,785","265,000",2.00%,"7,545",1
252,2008,50,63.1,"256,035","405,732","270,000",2.60%,"9,953",0
253,2012,50,59.0,"250,701","425,142","268,000",0.30%,"1,308",1
254,2016,50,60.2,"258,788","429,682","304,000",2.00%,"8,568",0

In [9]:
xform_pd["Primary:VEP Turnout Rate"]= xform_pd["Primary:VEP Turnout Rate"].str.replace("%","").astype(float) 
xform_pd

,Year,State,General:VEP Turnout Rate,General:Total Ballots Counted,VEP,Total registered,Primary:VEP Turnout Rate,Primary:Total Ballots Counted,Re-election
0,2000,0,59.0,"1,912,592","3,241,682","2,411,000",15.3,"489,573",0
1,2004,0,57.4,"1,890,317","3,292,608","2,418,000",26.0,"863,695",1
2,2008,0,61.0,"2,105,622","3,454,510","2,438,000",32.2,"1,088,835",0
3,2012,0,59.0,"2,088,138","3,539,217","2,556,000",24.8,"871,025",1
4,2016,0,59.1,"2,134,061","3,609,447","2,526,000",35.0,"1,260,551",0
...,...,...,...,...,...,...,...,...,...
250,2000,50,61.4,"221,685","361,078","240,000",2.0,"7,096",0
251,2004,50,66.3,"245,789","370,785","265,000",2.0,"7,545",1
252,2008,50,63.1,"256,035","405,732","270,000",2.6,"9,953",0
253,2012,50,59.0,"250,701","425,142","268,000",0.3,"1,308",1
254,2016,50,60.2,"258,788","429,682","304,000",2.0,"8,568",0

In [10]:
xform_pd["General:Total Ballots Counted"]= xform_pd["General:Total Ballots Counted"].str.replace(",","").astype(int) 
xform_pd

,Year,State,General:VEP Turnout Rate,General:Total Ballots Counted,VEP,Total registered,Primary:VEP Turnout Rate,Primary:Total Ballots Counted,Re-election
0,2000,0,59.0,1912592,"3,241,682","2,411,000",15.3,"489,573",0
1,2004,0,57.4,1890317,"3,292,608","2,418,000",26.0,"863,695",1
2,2008,0,61.0,2105622,"3,454,510","2,438,000",32.2,"1,088,835",0
3,2012,0,59.0,2088138,"3,539,217","2,556,000",24.8,"871,025",1
4,2016,0,59.1,2134061,"3,609,447","2,526,000",35.0,"1,260,551",0
...,...,...,...,...,...,...,...,...,...
250,2000,50,61.4,221685,"361,078","240,000",2.0,"7,096",0
251,2004,50,66.3,245789,"370,785","265,000",2.0,"7,545",1
252,2008,50,63.1,256035,"405,732","270,000",2.6,"9,953",0
253,2012,50,59.0,250701,"425,142","268,000",0.3,"1,308",1
254,2016,50,60.2,258788,"429,682","304,000",2.0,"8,568",0

In [11]:
xform_pd["VEP"]= xform_pd["VEP"].str.replace(",","").astype(int) 
xform_pd

,Year,State,General:VEP Turnout Rate,General:Total Ballots Counted,VEP,Total registered,Primary:VEP Turnout Rate,Primary:Total Ballots Counted,Re-election
0,2000,0,59.0,1912592,3241682,"2,411,000",15.3,"489,573",0
1,2004,0,57.4,1890317,3292608,"2,418,000",26.0,"863,695",1
2,2008,0,61.0,2105622,3454510,"2,438,000",32.2,"1,088,835",0
3,2012,0,59.0,2088138,3539217,"2,556,000",24.8,"871,025",1
4,2016,0,59.1,2134061,3609447,"2,526,000",35.0,"1,260,551",0
...,...,...,...,...,...,...,...,...,...
250,2000,50,61.4,221685,361078,"240,000",2.0,"7,096",0
251,2004,50,66.3,245789,370785,"265,000",2.0,"7,545",1
252,2008,50,63.1,256035,405732,"270,000",2.6,"9,953",0
253,2012,50,59.0,250701,425142,"268,000",0.3,"1,308",1
254,2016,50,60.2,258788,429682,"304,000",2.0,"8,568",0

In [12]:
xform_pd["Total registered"]= xform_pd["Total registered"].str.replace(",","").astype(int) 
xform_pd

,Year,State,General:VEP Turnout Rate,General:Total Ballots Counted,VEP,Total registered,Primary:VEP Turnout Rate,Primary:Total Ballots Counted,Re-election
0,2000,0,59.0,1912592,3241682,2411000,15.3,"489,573",0
1,2004,0,57.4,1890317,3292608,2418000,26.0,"863,695",1
2,2008,0,61.0,2105622,3454510,2438000,32.2,"1,088,835",0
3,2012,0,59.0,2088138,3539217,2556000,24.8,"871,025",1
4,2016,0,59.1,2134061,3609447,2526000,35.0,"1,260,551",0
...,...,...,...,...,...,...,...,...,...
250,2000,50,61.4,221685,361078,240000,2.0,"7,096",0
251,2004,50,66.3,245789,370785,265000,2.0,"7,545",1
252,2008,50,63.1,256035,405732,270000,2.6,"9,953",0
253,2012,50,59.0,250701,425142,268000,0.3,"1,308",1
254,2016,50,60.2,258788,429682,304000,2.0,"8,568",0

In [13]:
xform_pd["Primary:Total Ballots Counted"]= xform_pd["Primary:Total Ballots Counted"].str.replace(",","").astype(int) 
xform_pd

,Year,State,General:VEP Turnout Rate,General:Total Ballots Counted,VEP,Total registered,Primary:VEP Turnout Rate,Primary:Total Ballots Counted,Re-election
0,2000,0,59.0,1912592,3241682,2411000,15.3,489573,0
1,2004,0,57.4,1890317,3292608,2418000,26.0,863695,1
2,2008,0,61.0,2105622,3454510,2438000,32.2,1088835,0
3,2012,0,59.0,2088138,3539217,2556000,24.8,871025,1
4,2016,0,59.1,2134061,3609447,2526000,35.0,1260551,0
...,...,...,...,...,...,...,...,...,...
250,2000,50,61.4,221685,361078,240000,2.0,7096,0
251,2004,50,66.3,245789,370785,265000,2.0,7545,1
252,2008,50,63.1,256035,405732,270000,2.6,9953,0
253,2012,50,59.0,250701,425142,268000,0.3,1308,1
254,2016,50,60.2,258788,429682,304000,2.0,8568,0

In [14]:
# ======================================================
# ======================================================

# prepare transformed data file for Machine Learning
con_xform_pd = xform_pd

In [1]:
# https://github.com/pandas-profiling/pandas-profiling, 
#       used "pip install pandas-profiling[notebook]" -- failed with error
#       used "conda install -c conda-forge pandas-profiling"  -- successful
#profile = ProfileReport(con_xform_pd, title='Pandas Profiling Report', explorative=True)

In [48]:
# profile.to_file("your_report_Hubbel.html")

In [17]:
ml_data = con_xform_pd.drop(columns= ["General:VEP Turnout Rate", "Primary:VEP Turnout Rate"])
ml_data.head(2)

,Year,State,General:Total Ballots Counted,VEP,Total registered,Primary:Total Ballots Counted,Re-election
0,2000,0,1912592,3241682,2411000,489573,0
1,2004,0,1890317,3292608,2418000,863695,1

In [18]:
ml_data.to_csv("ml_data_Hubbel.csv", index=False)

In [28]:
# ======================================================
# ======================================================
ml_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Year                           255 non-null    int64
 1   State                          255 non-null    int32
 2   General:Total Ballots Counted  255 non-null    int32
 3   VEP                            255 non-null    int32
 4   Total registered               255 non-null    int32
 5   Primary:Total Ballots Counted  255 non-null    int32
 6   Re-election                    255 non-null    int64
dtypes: int32(5), int64(2)
memory usage: 9.1 KB

In [29]:

# load and summarize the dataset
from numpy import loadtxt
# load data
#dataset = loadtxt('ml_data_Hubbel.csv', delimiter=",")
#dataset.info()

In [34]:
### BEGIN SOLUTION
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.linear_model import HuberRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import TransformedTargetRegressor

# Assign X (data) and y (target)
# split into inputs and outputs
# X, y = dataset[:, :-1], dataset[:, -1]
# summarize dataset
# print(X.shape, y.shape)

#   r = ml_data['Re-election']
X = ml_data.drop(columns=['General:Total Ballots Counted'])
y = (ml_data["General:Total Ballots Counted"]/1000000).values.reshape(-1, 1)
# print(X.shape, y.shape, r.shape)
print(X.shape, y.shape)
### END SOLUTION

(255, 6) (255, 1)

In [35]:
X.head(2)

,Year,State,VEP,Total registered,Primary:Total Ballots Counted,Re-election
0,2000,0,3241682,2411000,489573,0
1,2004,0,3292608,2418000,863695,1

In [ ]:
# Split the data into training and testing

### BEGIN SOLUTION
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
### END SOLUTION

In [36]:
# prepare the model with input scaling
pipeline = Pipeline(
    steps=[('normalize', MinMaxScaler()), ('model', HuberRegressor())]
    )
pipeline

Pipeline(memory=None,
         steps=[('normalize', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('model',
                 HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True,
                                max_iter=100, tol=1e-05, warm_start=False))],
         verbose=False)

In [39]:
# prepare the model with target scaling
model = TransformedTargetRegressor(
    regressor=pipeline, transformer=MinMaxScaler()
    )
model

TransformedTargetRegressor(check_inverse=True, func=None, inverse_func=None,
                           regressor=Pipeline(memory=None,
                                              steps=[('normalize',
                                                      MinMaxScaler(copy=True,
                                                                   feature_range=(0,
                                                                                  1))),
                                                     ('model',
                                                      HuberRegressor(alpha=0.0001,
                                                                     epsilon=1.35,
                                                                     fit_intercept=True,
                                                                     max_iter=100,
                                                                     tol=1e-05,
                                                                     warm_start=False))],
                                              verbose=False),
                           transformer=MinMaxScaler(copy=True,
                                                    feature_range=(0, 1)))

In [40]:
# evaluate model
cv = KFold(n_splits=10, shuffle=True, random_state=1)
scores = cross_val_score(
    model, X, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
scores

array([-0.10261851, -0.15835043, -0.16871926, -0.13770621, -0.18926916,
       -0.11502964, -0.17384114, -0.16362395, -0.23922   , -0.13131329])

In [42]:
# normalizing input and output variables for regression.
from numpy import mean
from numpy import absolute
# convert scores to positive
scores = absolute(scores)
scores

array([0.10261851, 0.15835043, 0.16871926, 0.13770621, 0.18926916,
       0.11502964, 0.17384114, 0.16362395, 0.23922   , 0.13131329])

In [43]:
# Summarize the result

# If multioutput is 'raw_values', 
#        then mean absolute error is returned for each output separately. 
# If multioutput is 'uniform_average' or an ndarray of weights, 
#        then the weighted average of all output errors is returned. 
# MAE output is non-negative floating point.

s_mean = mean(scores)
print('Mean MAE: %.3f' % (s_mean))

Mean MAE: 0.158

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
### BEGIN SOLUTION
X_scaler = StandardScaler().fit(
    X_train[["VEP","Total registered","Primary:Total Ballots Counted"]]
    )

### END SOLUTION
X_scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [24]:
# Transform the training and testing data using the X_scaler and y_scaler models

### BEGIN SOLUTION
X_train_scaled = X_scaler.transform(X_train[["VEP","Total registered","Primary:Total Ballots Counted"]])
X_test_scaled = X_scaler.transform(X_test[["VEP","Total registered","Primary:Total Ballots Counted"]])

### END SOLUTION
X_train_scaled

array([[-5.16074871e-01, -5.32449062e-01, -4.98119942e-01],
       [-5.23315427e-01, -5.42022419e-01, -5.93002082e-01],
       [ 1.57315001e-01,  3.04687818e-01, -3.05908989e-01],
       [ 1.07494758e+00,  1.12622367e+00,  6.44868360e-01],
       [ 1.44318420e-01,  1.31303686e-01,  2.58707319e-02],
       [ 7.81275377e-01,  8.98590517e-01,  1.24426859e+00],
       [-6.48832418e-01, -6.81367948e-01, -5.30566238e-01],
       [ 1.15523177e+00,  1.33506468e+00,  2.00141396e+00],
       [-6.33281163e-01, -6.85977342e-01, -6.36475453e-01],
       [ 1.90378327e-01,  2.69585509e-01,  7.25272815e-01],
       [-1.54131430e-01, -7.50553412e-02, -5.77408820e-01],
       [-7.39275386e-02,  2.49330535e-02, -4.43237566e-02],
       [ 7.55488931e-01,  9.64540309e-01,  2.07181751e-01],
       [-6.50248124e-01, -7.02996643e-01, -3.61850612e-01],
       [-2.44026596e-01, -1.88162781e-01, -5.14510930e-01],
       [-4.22961691e-02, -2.36874219e-03, -6.06785925e-01],
       [-8.77867757e-01, -8.83117581e-01, -7.05254345e-01],
       [-5.16104983e-01, -5.51950345e-01, -6.72615788e-01],
       [ 7.43611485e-01,  8.73770703e-01,  5.21387460e-01],
       [-8.91933286e-01, -9.22120146e-01, -7.04060469e-01],
       [-7.79511096e-01, -8.51915529e-01, -6.97046059e-01],
       [-8.14805042e-01, -8.45178722e-01, -4.95322085e-01],
       [ 4.45039995e-01,  4.48642741e-01,  2.42241395e-01],
       [ 2.10242736e+00,  1.97080649e+00,  1.26913842e+00],
       [ 1.02311444e+00,  1.06771982e+00,  4.82550050e-01],
       [-3.82485681e-01, -3.01624789e-01, -4.78441406e-02],
       [-2.85761478e-01, -2.88151175e-01, -2.28729550e-01],
       [ 2.57580482e+00,  2.56116351e+00,  2.56851519e+00],
       [ 2.90409204e-02,  8.27277640e-02, -4.19765232e-01],
       [-4.11462483e-01, -4.27142136e-01, -6.14622093e-01],
       [-2.51686144e-02, -9.10554893e-03,  5.75650416e-02],
       [-8.59491542e-01, -8.91627232e-01, -6.84492530e-01],
       [-1.13639233e-01, -9.38474863e-02, -6.65246317e-01],
       [-8.88717837e-01, -9.13255927e-01, -6.14796523e-01],
       [ 7.35602854e-01,  9.32983688e-01,  4.18188499e-01],
       [ 4.32791852e+00,  4.24962002e+00,  6.32775740e+00],
       [-2.36917303e-02,  4.37251987e-02, -1.38291884e-01],
       [-2.00685782e-01, -1.42423409e-01, -4.55167535e-01],
       [-8.63243258e-01, -8.92336369e-01, -7.07635120e-01],
       [-9.05801898e-01, -9.43039704e-01, -7.10932234e-01],
       [ 4.12665643e-01,  3.71701316e-01, -1.05454090e-01],
       [ 2.32197568e-01,  3.56809428e-01, -8.29409972e-02],
       [-7.60452121e-01, -7.49445153e-01, -6.71380049e-01],
       [-7.63527768e-01, -7.74264967e-01, -4.93457623e-01],
       [-5.53963880e-01, -6.24636944e-01, -5.12989901e-01],
       [-4.76762031e-01, -4.34588080e-01, -6.13052224e-01],
       [-8.91925878e-01, -9.24247559e-01, -6.85780210e-01],
       [-4.25831817e-02,  5.50713995e-02, -4.67305534e-01],
       [-6.97171697e-01, -7.62209629e-01, -5.54622066e-01],
       [-4.53973326e-01, -4.09413697e-01, -6.02973274e-01],
       [ 3.46612596e-01,  3.40144695e-01, -5.29746805e-01],
       [-2.29119147e-01, -2.10146045e-01, -6.26680242e-01],
       [-3.45191074e-02,  1.15348091e-01,  5.08762344e-02],
       [ 6.68316680e-01,  8.49305457e-01,  9.75672824e-01],
       [-6.92545625e-02,  6.57084628e-02, -6.78511520e-01],
       [ 1.26814864e+00,  1.25918696e+00,  1.75127289e+00],
       [-6.70399468e-01, -7.72846692e-01, -6.47805647e-01],
       [-2.17400860e-01, -1.73270892e-01, -3.36894726e-01],
       [-1.66539646e-01, -1.63697535e-01,  1.27679680e-01],
       [-4.62493849e-01, -4.50189106e-01, -4.41457341e-01],
       [ 1.83069788e+00,  1.88606456e+00,  1.18173972e+00],
       [-1.19910016e-01, -1.42068840e-01, -2.30293482e-02],
       [-1.05654499e-01, -1.15121613e-01,  1.50652492e-01],
       [-6.42104709e-01, -7.03351212e-01, -4.61539267e-01],
       [-3.43680191e-01, -3.87785001e-01, -4.06882999e-01],
       [-8.90492010e-01, -9.33111778e-01, -7.15419348e-01],
       [-7.42118683e-01, -7.49090584e-01, -7.11926097e-01],
       [-8.52333195e-01, -8.80990168e-01, -6.90624712e-01],
       [-7.65980160e-01, -7.93057112e-01, -6.11734309e-01],
       [-8.04252012e-01, -8.37378209e-01, -5.73732612e-01],
       [-5.86586292e-01, -6.21445825e-01, -5.90941483e-01],
       [-1.03797162e-01, -1.47032803e-01, -5.31194961e-01],
       [ 3.19461762e-02,  1.50095831e-01,  9.22079416e-01],
       [-6.58348045e-01, -6.96614405e-01, -4.21484724e-01],
       [-1.83638763e-01, -1.64052104e-01, -5.72702312e-01],
       [ 2.19351305e-01,  1.47968419e-01,  5.10165536e-02],
       [-1.29513109e-01, -1.32495483e-01,  2.60801517e-01],
       [-4.87048123e-01, -4.64726426e-01, -2.68777892e-01],
       [-4.01557322e-01, -4.03740596e-01, -3.23255854e-01],
       [-7.54971399e-01, -7.60082216e-01, -3.05777973e-01],
       [-3.66179255e-01, -3.90621552e-01, -1.33247370e-01],
       [-6.77377865e-01, -7.08669743e-01, -5.23042493e-01],
       [-7.46083806e-01, -7.71782986e-01, -5.74852840e-01],
       [-6.99539969e-01, -7.21434219e-01, -5.39934289e-01],
       [ 6.72876795e-02,  1.71724527e-01, -4.63364192e-01],
       [ 2.69032684e-01,  1.91934947e-01, -4.09511852e-01],
       [ 1.31438850e+00,  1.38115862e+00,  3.87682639e-01],
       [ 6.53643844e-02,  3.55701168e-02,  3.34277615e-01],
       [-8.13564030e-01, -8.43051309e-01, -6.07778237e-01],
       [-7.13274514e-01, -7.48026878e-01, -5.21785047e-01],
       [-8.68958656e-01, -8.79217325e-01, -6.36380098e-01],
       [ 3.80655732e-01,  2.90859635e-01,  6.82927425e-01],
       [-6.85538486e-01, -6.96259836e-01, -5.25784532e-01],
       [-8.92510418e-01, -9.23538422e-01, -6.97071642e-01],
       [-4.74268057e-01, -3.92039827e-01, -4.91662932e-01],
       [ 4.22223808e-01,  5.05728313e-01, -3.17075607e-01],
       [ 4.66734689e+00,  4.41662191e+00,  3.41429734e+00],
       [-8.76742410e-01, -9.05809983e-01, -5.63931199e-01],
       [ 2.12252828e+00,  2.13780839e+00,  7.67110420e-01],
       [-5.31159403e-01, -5.53723188e-01, -6.66140173e-01],
       [-8.26785728e-01, -8.55461217e-01, -5.89656128e-01],
       [ 1.39728370e-01,  1.10029560e-01, -2.30178482e-01],
       [ 2.03991979e+00,  2.08285023e+00,  2.59277569e+00],
       [-1.83286031e-01, -1.60860985e-01, -2.41195477e-01],
       [ 1.32388262e+00,  1.42157946e+00,  1.82319074e+00],
       [ 2.05202379e+00,  2.02966491e+00,  8.59007871e-01],
       [-8.77960003e-01, -8.91627232e-01, -6.66547176e-01],
       [-7.79252522e-01, -8.05467019e-01, -4.09138184e-01],
       [ 9.90372540e-01,  9.43620751e-01,  1.24229094e+00],
       [-1.46296535e-01, -1.21858420e-01, -4.11762650e-02],
       [ 8.73845360e-02,  1.22084898e-01,  1.26999015e-01],
       [ 5.86742251e-01,  6.62093144e-01,  8.89089409e-02],
       [-8.07008863e-01, -8.32059677e-01, -5.31327528e-01],
       [ 3.35530469e-01,  3.72410454e-01,  4.27404603e-01],
       [-8.09606076e-01, -8.26741146e-01, -5.49082946e-01],
       [ 9.79260954e-02,  1.41586181e-01,  3.58598577e-01],
       [ 2.49724223e+00,  2.37714231e+00,  2.43957657e+00],
       [ 2.19207709e+00,  2.12291650e+00, -5.73046521e-01],
       [-5.31353931e-01, -5.69678783e-01, -6.67817802e-01],
       [-3.74868495e-01, -4.03031459e-01, -2.96040905e-01],
       [-6.52018473e-01, -7.04414918e-01, -3.70209296e-01],
       [-8.77518610e-01, -9.05809983e-01, -6.98121323e-01],
       [-8.76731656e-01, -8.82053875e-01, -7.05921055e-01],
       [ 6.97650754e-01,  7.43289393e-01,  3.65233117e-01],
       [-2.31481445e-01, -1.72561755e-01, -3.88539945e-01],
       [-5.06802285e-01, -5.07983816e-01, -6.93286900e-01],
       [-8.74190602e-01, -9.01555157e-01, -6.36378547e-01],
       [ 4.02267709e-01,  4.64598335e-01, -5.10551758e-01],
       [-2.07665374e-01, -2.29292759e-01, -1.85980258e-01],
       [-8.69784565e-01, -9.00136882e-01, -7.05475290e-01],
       [ 5.65200469e-02, -3.10888130e-02, -3.19654069e-01],
       [-7.50040326e-01, -8.40214759e-01, -6.79924791e-01],
       [-6.49954420e-01, -6.90232167e-01, -5.05600273e-01],
       [-8.25018724e-01, -8.44115016e-01, -5.26814056e-01],
       [-4.97033581e-01, -5.61169133e-01, -2.94568717e-01],
       [ 4.55104555e-01,  4.93672975e-01,  7.75276068e-01],
       [ 1.19877660e-01,  7.27998383e-02,  6.21600180e-01],
       [-8.82359110e-01, -9.11128514e-01, -5.96465874e-01],
       [-7.99893531e-01, -8.22131752e-01, -4.96834587e-01],
       [-8.45552671e-01, -8.67161986e-01, -6.45315563e-01],
       [-1.27491658e-02, -1.69060620e-02, -4.45317282e-01],
       [-7.31268603e-01, -7.63982472e-01, -6.81801657e-01],
       [ 6.71186568e-01,  7.06414240e-01,  8.81600038e-01],
       [ 1.10206459e-01,  1.39458768e-01,  6.54358125e-01],
       [ 3.55665084e-01,  2.22782430e-01,  2.69790673e-03],
       [ 4.23118478e-02, -5.69723336e-02, -3.53791949e-01],
       [-8.56642924e-01, -8.77799049e-01, -7.13332390e-01],
       [ 9.84109818e-02,  7.55918353e-03,  1.97253198e-01],
       [-2.69380491e-01, -2.66877049e-01,  1.15562613e-01],
       [-9.03482138e-01, -9.34175485e-01, -7.10584149e-01],
       [-8.50922507e-01, -8.71416811e-01, -5.85928754e-01],
       [-8.79591744e-01, -9.02618864e-01, -5.90937607e-01],
       [ 7.64994521e-01,  8.13494011e-01,  1.06528330e+00],
       [-7.57199630e-01, -8.34187090e-01, -7.08504169e-01],
       [ 2.86022761e+00,  2.78312356e+00,  8.64786542e-01],
       [ 2.23293039e+00,  2.19914879e+00,  5.83012399e-01],
       [-2.20387368e-01, -2.11564320e-01, -3.94445756e-01],
       [ 4.05811927e+00,  4.00425842e+00,  4.38863591e+00],
       [-7.69826034e-01, -8.43051309e-01, -6.96601844e-01],
       [-1.58813965e-01, -1.49160215e-01, -2.46927633e-01],
       [ 1.96650598e+00,  1.82507873e+00,  1.71520930e+00],
       [-7.33631364e-03,  6.92541505e-02,  4.65317921e-01],
       [-3.46772806e-01, -3.32826841e-01,  1.91010156e-01],
       [ 1.21175461e+00,  1.26982403e+00,  1.22977307e+00],
       [ 8.75931638e-02,  1.53641519e-01,  5.02404830e-01],
       [-8.41965611e-01, -8.69643968e-01, -6.02799619e-01],
       [-6.66453224e-01, -6.95905267e-01, -5.11584383e-01],
       [-6.59824929e-01, -7.13988275e-01, -4.26022228e-01],
       [-2.05230666e-01, -1.70788911e-01, -4.68588052e-02],
       [ 5.09137724e-01,  6.11389809e-01,  8.52964842e-01],
       [-7.42886519e-01, -7.57600234e-01, -2.95895159e-01],
       [-8.32567801e-01, -8.64680005e-01, -5.35019241e-01],
       [ 3.61288954e-01,  4.20277238e-01, -4.68611309e-02],
       [-2.09848263e-02, -4.14158607e-03, -2.53827307e-01],
       [-7.39163959e-01, -7.33844126e-01, -6.66313828e-01],
       [-1.29575721e-01,  6.39356189e-02, -5.67008143e-01],
       [-2.38682570e-01, -2.27165346e-01, -1.30467921e-03],
       [-2.00824867e-01, -1.82489680e-01,  4.14841506e-02],
       [ 1.66936734e-01,  1.41231612e-01,  6.39718413e-01],
       [ 1.81153297e-01,  1.24566880e-01,  2.39404777e-01],
       [ 2.77293452e-03, -1.09803081e-01, -3.55174209e-01],
       [-4.97702002e-01, -4.92737359e-01, -3.19092792e-01],
       [-8.89407050e-01, -9.20347303e-01, -7.09791075e-01],
       [ 3.71225236e+00,  3.60288657e+00,  5.39511534e+00],
       [-3.14325804e-01, -2.88505744e-01, -2.40192311e-01],
       [ 8.43275292e-02,  4.65617489e-02,  3.62093378e-01],
       [ 9.14010396e-02,  2.06826835e-01, -1.76371881e-01],
       [ 1.40738291e-01,  8.69825893e-02,  1.32545113e-01],
       [-2.25977303e-01, -1.79653130e-01, -2.93526013e-01],
       [ 1.09581347e+00,  1.14466125e+00,  1.82496683e+00],
       [-5.40749177e-02, -2.54157126e-02,  2.32712093e-01]])

In [25]:
X_train[["VEP","Total registered","Primary:Total Ballots Counted"]] = X_train_scaled
X_test[["VEP","Total registered","Primary:Total Ballots Counted"]] = X_test_scaled

C:\Users\VEA\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\VEA\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
C:\Users\VEA\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [30]:
X_test

,Year,State,VEP,Total registered,Primary:Total Ballots Counted,Re-election
190,2000,38,1.179477,1.045027,1.190641,0
6,2004,1,-0.884044,-0.909710,-0.702975,1
79,2016,15,-0.445182,-0.440616,-0.438909,0
205,2000,41,-0.861013,-0.894818,-0.627641,0
117,2008,23,-0.098280,0.011105,-0.501564,0
...,...,...,...,...,...,...
60,2000,12,-0.782411,-0.826387,-0.620767,0
101,2004,20,-0.084629,-0.079310,-0.221108,1
172,2008,34,-0.871465,-0.886663,-0.694039,0
248,2012,49,0.013855,0.148323,0.127111,1
126,2004,25,0.007066,0.154705,-0.295172,1

In [ ]:
### BEGIN SOLUTION
from sklearn.metrics import mean_squared_error

predictions = model.predict(X_test)

MSE = mean_squared_error(y_test, predictions)
r2 = model.score(X_test, y_test)
### END SOLUTION

print(f"MSE: {MSE}, R2: {r2}")

NameError: name 'model' is not defined